<a href="https://colab.research.google.com/github/KPorus/machine-learning-and-python/blob/main/python_basic_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# prime number checker

In [ ]:
x=int(input("enter a number: "))

def prime(x):
    for i in range(2,x):
        if x%i==0:
            return False
    return True

print(prime(x))

enter a number4
False


#list Manipulation

In [ ]:
import pandas as pd
li = [10,20,30,40,50]

df = pd.DataFrame(li)
print(df)
print(f"max:{df[0].max()}")
print(f"min:{df[0].min()}")
print(f"mean:{df[0].mean()}")

    0
0  10
1  20
2  30
3  40
4  50
max:50
min:10
mean:30.0


#reverse string

In [ ]:
s = "hello"
while(len(s)>0):
    print(s[-1],end="")
    s = s[:-1]

olleh

#Multiplication Table using nested loop

In [ ]:
x = int(input("enter a number: "))

for i in range(1,x+1):
    for j in range(1,11):
        print(f"{i} x {j} = {i*j}",end="\n ")

enter a number: 5
1 x 1 = 1
 1 x 2 = 2
 1 x 3 = 3
 1 x 4 = 4
 1 x 5 = 5
 1 x 6 = 6
 1 x 7 = 7
 1 x 8 = 8
 1 x 9 = 9
 1 x 10 = 10
 2 x 1 = 2
 2 x 2 = 4
 2 x 3 = 6
 2 x 4 = 8
 2 x 5 = 10
 2 x 6 = 12
 2 x 7 = 14
 2 x 8 = 16
 2 x 9 = 18
 2 x 10 = 20
 3 x 1 = 3
 3 x 2 = 6
 3 x 3 = 9
 3 x 4 = 12
 3 x 5 = 15
 3 x 6 = 18
 3 x 7 = 21
 3 x 8 = 24
 3 x 9 = 27
 3 x 10 = 30
 4 x 1 = 4
 4 x 2 = 8
 4 x 3 = 12
 4 x 4 = 16
 4 x 5 = 20
 4 x 6 = 24
 4 x 7 = 28
 4 x 8 = 32
 4 x 9 = 36
 4 x 10 = 40
 5 x 1 = 5
 5 x 2 = 10
 5 x 3 = 15
 5 x 4 = 20
 5 x 5 = 25
 5 x 6 = 30
 5 x 7 = 35
 5 x 8 = 40
 5 x 9 = 45
 5 x 10 = 50
 

#prints Patterns


In [ ]:
x = int(input("enter a number: "))

for i in range(1,x+1):
    for j in range(1,i+1):
        print("*",end=" ")
    print()

enter a number: 5
* 
* * 
* * * 
* * * * 
* * * * * 


#Matrix Multiplication

In [ ]:
x = [2,3,4]
y = [5,6,7]

for i in range(len(x)):
    for j in range(len(y)):
        print(x[i]*y[j],end="\n")
    print()

10
12
14

15
18
21

20
24
28



#Chessboard pattern

In [ ]:
import numpy as np

chess = np.zeros((8,8),dtype=int)
print(chess)
chess[1::2,::2] = 1
chess[::2,1::2] = 1
print(chess)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Number Pyramid

In [ ]:
x = int(input("enter a number: "))

for i in range(1,x+1):
    for j in range(1,i+1):
      print(i, end=" ")
    print()


enter a number: 5
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


#List sum

In [ ]:
x = [x for x in range(1,11)]
print(x)
print(sum(x))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
55


#List avg

In [ ]:
x = [x for x in range(1,11)]
print(x)
print(sum(x)/len(x))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
5.5


#list max and min

In [ ]:
x = [i for i in range(10)]
print(x)
print(max(x))
print(min(x))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
9
0


#List sort

In [ ]:
import random
x = [random.randint(1, 10) for _ in range(10)]
print(x)
x.sort()
print(x)

[1, 6, 3, 9, 4, 8, 5, 1, 8, 6]
[1, 1, 3, 4, 5, 6, 6, 8, 8, 9]


#list filter

In [ ]:
x = [i for i in range(10)]
print(x)
x = [i for i in x if i%2==0]
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]


#list reversed

In [ ]:
import random
x = [random.randint(1, 10) for _ in range(10)]
print(x)
x.sort(reverse=True)
print(x)

[5, 7, 10, 1, 10, 5, 3, 10, 8, 8]
[10, 10, 10, 8, 8, 7, 5, 5, 3, 1]


#list manipulation

In [ ]:
import random
x = [random.randint(1,10) for _ in range(10)]
print(x)
y = [random.randint(1,10) for _ in range(10)]
print(y)

z = list(set(x) & set(y))
print(z)

[5, 10, 6, 3, 10, 4, 5, 6, 3, 4]
[8, 1, 2, 5, 5, 5, 5, 9, 2, 8]
[5]


#list element count

In [ ]:
import random
x = [random.randint(1, 10) for _ in range(1,11)]

for i in x:
    print(f"{i} : {x.count(i)}")

4 : 1
7 : 1
10 : 4
1 : 4
10 : 4
10 : 4
10 : 4
1 : 4
1 : 4
1 : 4


#list duplicate removing without change the order

In [ ]:
import random
x = [random.randint(1, 10) for _ in range(1,11)]
y = x.copy()
print(y)
seen = set()
res = []
for i in x:
  if i not in seen:
    res.append(i)
    seen.add(i)
print(res)


[2, 5, 4, 9, 5, 9, 6, 2, 8, 3]
[2, 5, 4, 9, 6, 8, 3]


#List Comprehension

In [ ]:
x = [i ** 2 for i in range(1,11)]
print(x)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
